package com.biblio.bnr.entity;

public enum GenreLivre {
    ROMANS, NOUVELLES, CONTES, POESIE,
    ESSAIS, BIOGRAPHIES, AUTOBIOGRAPHIES, DOCUMENTAIRES,
    SCIENCE_FICTION, FANTAISIE, MYSTERE, POLICIER, ROMANCE, HORREUR, AVENTURE,
    SCIENCES, HISTOIRE, PHILOSOPHIE, PSYCHOLOGIE, ECONOMIE, POLITIQUE,
    LIVRES_ENFANTS, LIVRES_ADOLESCENTS,
    LIVRES_POCHE, LIVRES_RELIES, LIVRES_ELECTRONIQUES,
    LIVRES_RELIGIEUX, LIVRES_SPIRITUELS,
    BEAUX_ARTS, MUSIQUE, CINEMA, THEATRE,
    DICTIONNAIRES, ENCYCLOPEDIRES, GUIDES_PRATIQUES,
    CUISINE, VOYAGE, JARDINAGE, SPORTS
}
